development:
  sessions:
    default:
      database: bible_everyday_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: bible_everyday_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: bible_everyday
      hosts:
        - localhost:27017